### ISSUE TITLE
Must use Python 3.9.x... 3.10+ not supported!

### ISSUE THREAD

**Issue by ReenigneArcher** [ReenigneArcher/RetroArcher.bundle#169]
### Describe the Bug

The current code is not compatible with Python 3.10 or newer. You must use Python 3.9.x!

### Additional Context

```txt
c:\Users\someone\AppData\Local\Plex Media Server\Plug-ins\RetroArcher.bundle\Contents\Code\retroarcher>py -3 retroarcher.py --scan
Traceback (most recent call last):
  File "c:\Users\someone\AppData\Local\Plex Media Server\Plug-ins\RetroArcher.bundle\Contents\Code\retroarcher\retroarcher.py", line 1300, in <module>
    import psutil
  File "C:\Users\someone\AppData\Local\Plex Media Server\Plug-ins\RetroArcher.bundle\Contents\Libraries\Modules\psutil__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\someone\AppData\Local\Plex Media Server\Plug-ins\RetroArcher.bundle\Contents\Libraries\Modules\psutil_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ModuleNotFoundError: No module named 'psutil._psutil_windows'
```

### RetroArcher Server Operating System and Version

Windows

### Plex Media Server Version

-

### RetroArcher Version

1.2.5

### Client Device

-

**Comment by FlattusBlastus** [comment]
Oh dear! I just reformatted my home server to Windows Server 2022. I think I can do a downgrade and not kill my other services. Running Python 3.11.1.
